name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "This is your first issue on aOS! Please make sure to include as many details as possible"
        pr-message: "Thank you for contributing to aOS! As this is your first time, your contribution will take a little longer to process"
